name: mimar_ai
description: "Mimar-AI: Deprem Riski Analiz UygulamasÄ±"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_generative_ai: ^0.4.7
  image_picker: ^1.2.1
  file_picker: ^8.0.0
  path_provider: ^2.1.5
  path: ^1.9.0
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.3
  pdf: ^3.11.1
  printing: ^5.13.2
  share_plus: ^10.0.2
  intl: ^0.19.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  fl_chart: ^0.69.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.5

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.4
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3

  flutter_image_compress: ^2.3.0
  image: ^4.1.7
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  url_launcher: ^6.3.1
  http: ^1.2.2
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  youtube_player_flutter: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/.env

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
          weight: 400
